---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: rsyslog-centos-6
    box: centos/6
  - name: rsyslog-centos-7
    box: centos/7
  - name: rsyslog-debian-jessie64
    box: debian/jessie64
  - name: rsyslog-debian-buster64
    box: desc/buster64
  - name: rsyslog-fedora-27-cloud-base
    box: fedora/27-cloud-base
  - name: rsyslog-fedora-28-cloud-base
    box: fedora/28-cloud-base
  - name: rsyslog-opensuse-openSUSE-42-2-x86-64
    box: opensuse/openSUSE-42.2-x86_64
  - name: rsyslog-ubuntu-trusty
    box: ubuntu/trusty64
  - name: rsyslog-ubuntu-artful
    box: ubuntu/artful64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: goss
  lint:
    name: yamllint
